#define FRAME_SIZE 256 //256 bytes
#define NUM_FRAMES 256
#define TLB_SIZE 16
#define PAGE_SIZE 256
#define VM_SIZE 256
#define RAM_SIZE (FRAME_SIZE * NUM_FRAMES)
#define PAGE_MASK 0xFFFF
#define OFFSET_MASK 0xFF
#define PAGE_TABLE_SIZE 256
#define READ_SIZE 256
